### ISSUE TITLE
bug(v0.4.x): adding certain chart options crashes the process

### ISSUE THREAD

**Issue by DRoet** [victorgarciaesgi/vue-chart-3#9] opened 2021-07-05 19:49 UTC
Using a simple chart inside Vue 2, the newer version crashes my process once I add `options.scales` to my chart. Other properties such as `options.onClick()` and `options.plugins` seem to work fine

```vue
<template>
    <BarChart :data="data" :options="options"/>
</template>


<script>
   export default {
      components: {
         BarChart,
      },
      data() {
         return {
            options: {
               scales: {}, // boom
            },
         }
      },
   }
</script>
```

This was working fine back on `v0.1.7`

**Comment by victorgarciaesgi** [comment] 2021-07-06 07:49
Hi @DRoet, what is the error you have on 0.2.x ? I will look at it

**Comment by DRoet** [comment] 2021-07-06 08:00
The weird thing is that it doesn't throw an error, it just crashes my browser tab like something is being called recursively.

**Comment by victorgarciaesgi** [comment] 2021-07-06 08:14
Ok I think I found it and it's weird, Chart.js behave strangely when I want to make things reactive. 
I just put a watcher on options to update the chart if the options changes, and removing the watcher seems to fix the problem

**Comment by victorgarciaesgi** [comment] 2021-07-06 08:19
I've got errors only with `CategoryScale` so it's weird, you can try 0.2.14 I removed reactive options,

**Comment by DRoet** [comment] 2021-07-07 08:21
This issue is now resolved, however please take a look at https://github.com/victorgarciaesgi/vue-chart-3/commit/dfec8989388d49b9a74f4fe24c938a11948758c6#r53151569

**Comment by DRoet** [comment] 2021-07-19 07:46
@victorgarciaesgi unfortunately this regression can back in the latest version (0.4.1). As soon as you add `options.scales` to the charts the browser tab crashes

**Comment by victorgarciaesgi** [comment] 2021-07-19 07:53
@DRoet What options do you use? I use options in my exemples and it works :(

**Comment by DRoet** [comment] 2021-07-19 08:01
It happens as soon as I add the scales key, the value doesn't even matter. Is your example using Vue 2? I am using:

```js
"@vue/composition-api": "1.0.3",
"chart.js": "3.4.1",
"chartjs-adapter-date-fns": "2.0.0",
"vue": "2.6.14",
"vue-chart-3": "0.4.1",
```

**Comment by victorgarciaesgi** [comment] 2021-07-19 08:18
My template in local is using Vue 2. I'm trying to make a repro and codesandbox with there seems to be a bug with vue-demi and vue 2 on CodeSandbox 
https://codesandbox.io/s/demo-vue-chart-3-vue-2-pvogd

Otherwise, the test project is here if you want to try https://github.com/victorgarciaesgi/vue-chart-3/tree/main/packages/test/vue2

**Comment by victorgarciaesgi** [comment] 2021-07-19 08:28
I managed to get it working on a nuxt container 

https://codesandbox.io/s/zealous-turing-0g0je?file=/pages/index.vue

**Comment by DRoet** [comment] 2021-07-19 08:38
Ah it seems to be a problem specific to the (older) options-API, all your examples are fully using the composition API:

example:

```vue
<template>
  <div id="app" style="width: 400px">
    <BarChart :width="400" ref="doughnutRef" :chart-data="data" :options="options" />
  </div>
</template>

<script>
import { Chart, registerables } from 'chart.js';
import { BarChart } from 'vue-chart-3';

Chart.register(...registerables);

export default {
  name: 'App',
  components: {
    BarChart,
  },
  data () {
    return {
      data: {
        labels: ['Paris', 'Nîmes', 'Toulon', 'Perpignan', 'Autre'],
        datasets: [
          {
            data: [30, 40, 60, 70, 5],
            backgroundColor: ['#77CEFF', '#0079AF', '#123E6B', '#97B0C4', '#A5C8ED'],
          },
        ],
      },
      options: {
        scales: {},  // boom
        plugins: {
          legend: {
            position: 'top',
          },
          title: {
            display: true,
            text: 'Chart.js Doughnut Chart',
          },
        },
      }
    }
  }
}
</script>
```

**Comment by victorgarciaesgi** [comment] 2021-07-19 08:43
That's weird, normaly both apis are compatibles with each other

**Comment by victorgarciaesgi** [comment] 2021-07-19 08:50
You're right it's completly crashing my tabs, I don't know how to debug this bug

**Comment by victorgarciaesgi** [comment] 2021-07-19 08:54
I found a workaround @DRoet . If your `options` is a computed data, it will not crash

**Comment by victorgarciaesgi** [comment] 2021-07-19 09:05
I updated the docs to warn about using options in data or ref (same error using `ref`). Still weird bug and i don't know if this is Vue related or Chart.js related

**Comment by victorgarciaesgi** [comment] 2021-07-19 09:47
@DRoet Fixed the bug on `0.4.3` !!! I found where it cames from. Chart.js was mutating `options` so it triggered a callback loop between the watcher and the data. Computed didn't had this problem because it was not mutated.

Now it's working fine :D

**Comment by DRoet** [comment] 2021-07-19 10:00
Awesome thank you for fixing this 😄

**Comment by victorgarciaesgi** [comment] 2021-07-19 10:10
And thanks to you for reporting it 😄

**Comment by DRoet** [comment] 2021-07-19 12:19
welp I spoke too soon and should've tested this first, I am getting an error on my end when trying to run the latest version:

```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in data(): "Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function."

found in

---> <BarChart>
```

and:

```
Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.
    at assert (vue-composition-api.esm.js?a6f4:34)
    at getVueConstructor (vue-composition-api.esm.js?a6f4:118)
    at isComponentInstance (vue-composition-api.esm.js?a6f4:237)
    at setupAccessControl (vue-composition-api.esm.js?a6f4:515)
    at reactive (vue-composition-api.esm.js?a6f4:723)
    at Module.ref (vue-composition-api.esm.js?a6f4:399)
    at setup (components.js?0801:41)
    at mergedSetupFn (vue-composition-api.mjs?ed09:1899)
    at eval (vue-composition-api.mjs?ed09:1678)
    at activateCurrentInstance (vue-composition-api.mjs?ed09:1601)

&& 

vue.runtime.esm.js?2b0e:619 [Vue warn]: `createElement()` has been called outside of render function.
```

**Comment by victorgarciaesgi** [comment] 2021-07-19 12:21
Ah yeah that's normal on Vue 2, did you registered `@vue/composition-api` ?

**Comment by DRoet** [comment] 2021-07-19 12:24
Yeah I have `Vue.use(VueCompositionAPI)` somewhere on top of my main.js file. the stacktrace however mentions `components.js` which is located within this library

**Comment by victorgarciaesgi** [comment] 2021-07-19 12:29
Try deleting and reinstalling your dependencies, i'm not reproducing it on my Vue 2 project.
And even weirder because there is not even the need to call `Vue.use(compositionApi)` because I use `install()` from vue-demi which register it itself

**Comment by victorgarciaesgi** [comment] 2021-07-19 12:46
By the way are you trying on local or on Codesandbox? Because the later doesn't support vue-demi. I didn't manage to get it working yet with Vue 2

**Comment by DRoet** [comment] 2021-07-19 12:52
Local, I'm 99% sure its not a dependency issue since I run things in docker containers which ensures I always get fresh packages when my lockfile changes

**Comment by DRoet** [comment] 2021-07-19 13:00
ah its the vue-demi version bump that seems to cause it, I used `yarn resolutions` to pin the version to 0.9.1 and now it seems fine. maybe related to https://github.com/vueuse/vue-demi/issues/76?

**Comment by victorgarciaesgi** [comment] 2021-07-19 13:01
Yeah I found this issue too this may be it, I will downgrade the vue-demi version until the fix is merged

**Comment by DRoet** [comment] 2021-07-19 13:02
just a typical Monday am I right? 😄

**Comment by victorgarciaesgi** [comment] 2021-07-19 13:07
Ahaha yeah typical monday 😩

**Closed** 2021-07-19 14:07 UTC
